######################################################################
#
# File name : gty_64_156_28G_example_top_sim_wave.do
# Created on: Mon Jun 11 11:18:58 PDT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
