######################################################################
#
# File name : gty_64_156_28G_example_top_sim_compile.do
# Created on: Mon Jun 11 11:18:52 PDT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lwork
vlib questa_lmsim

vlib questa_lmsim/gtwizard_ultrascale_v1_7_3
vlib questa_lmsim/xil_defaultlib

vmap gtwizard_ultrascale_v1_7_3 questa_lmsim/gtwizard_ultrascale_v1_7_3
vmap xil_defaultlib questa_lmsim/xil_defaultlib

vlog -64 -incr -work gtwizard_ultrascale_v1_7_3  "+incdir+../../../imports" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
"../../../gty_64_156_28G_ex.ip_user_files/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \

#vlog -64 -incr -fsmdebug -novopt -timescale 1ns/100ps -sv -work xil_defaultlib  "+incdir+../../../imports" \

vlog -64 -sv -work xil_defaultlib  "+incdir+../../../imports" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gty_64_156_28G_gtye4_channel_wrapper.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gtwizard_ultrascale_v1_7_gtye4_common.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gty_64_156_28G_gtye4_common_wrapper.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gty_64_156_28G_gtwizard_gtye4.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gty_64_156_28G_gtwizard_top.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G/sim/gty_64_156_28G.v" \
"../../../gty_64_156_28G_ex.srcs/sources_1/ip/gty_64_156_28G_vio_0/sim/gty_64_156_28G_vio_0.v" \
"../../../imports/gty_64_156_28G_example_bit_sync.v" \
"../../../imports/gty_64_156_28G_example_checking_raw.v" \
"../../../imports/gty_64_156_28G_example_gtwiz_userclk_rx.v" \
"../../../imports/gty_64_156_28G_example_gtwiz_userclk_tx.v" \
"../../../imports/gty_64_156_28G_example_init.v" \
"../../../imports/gty_64_156_28G_example_reset_sync.v" \
"../../../imports/gty_64_156_28G_example_stimulus_raw.v" \
"../../../imports/gty_64_156_28G_example_top.v" \
"../../../imports/gty_64_156_28G_example_wrapper.v" \
"../../../imports/gty_64_156_28G_prbs_any.v" \
"../../../imports/gty_64_156_28G_example_top_sim.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

