######################################################################
#
# File name : gty_64_156_28G_example_top_sim_elaborate.do
# Created on: Mon Jun 11 11:18:53 PDT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.gty_64_156_28G_example_top_sim xil_defaultlib.glbl -o gty_64_156_28G_example_top_sim_opt
