proc compile_vsim {} {
if [file exists altlib] {vdel -lib altlib -all}
vlib altlib

if [file exists tblib] {vdel -lib tblib -all}
vlib tblib
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../common/common_pkg.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../common/common_env_pkg.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel/mm/ral/drp_reg_pkg.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel/mm/mm_pkg.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel/toplevel_pkg.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel/mm/mm_if.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel_test/toplevel_test_pkg.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel_tb/toplevel_tb.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../toplevel_tb/toplevel_th.sv
 vlog -fsmdebug -novopt -timescale 1ns/100ps +incdir+../ +define+ -sv -work tblib ./../../vio_regs.v
source gty_64_156_28G_example_top_sim_compile.do
}
proc run_vsim {} {
######################################################################
#
# File name : gty_64_156_28G_example_top_sim_elaborate.do
# Created on: Mon Jun 11 11:18:53 PDT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
#vopt -64 +acc=npr -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.gty_64_156_28G_example_top_sim xil_defaultlib.glbl -o gty_64_156_28G_example_top_sim_opt

vopt -64 +acc=npr -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L tblib -L altlib -work xil_defaultlib +transport_int_delays +transport_path_delays +notimingchecks xil_defaultlib.glbl tblib.toplevel_tb -o toplevel_tb_opt

######################################################################
#
# File name : gty_64_156_28G_example_top_sim_simulate.do
# Created on: Mon Jun 11 11:18:58 PDT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib toplevel_tb_opt +UVM_TESTNAME=base_test +UVM_VERBOSITY=UVM_FULL -l base_test.log -wlf base_test.wlf -sv_seed 12345


set NumericStdNoWarnings 1
set StdArithNoWarnings 1

#do {gty_64_156_28G_example_top_sim_wave.do}

view wave
view structure
view signals

#do {gty_64_156_28G_example_top_sim.udo}

run 1000ns
#vsim -novopt -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L tblib -L altlib +transport_int_delays +transport_path_delays +notimingchecks -t ps xil_defaultlib.glbl tblib.toplevel_tb +UVM_TESTNAME=base_test +UVM_VERBOSITY=UVM_FULL -l base_test.log -wlf base_test.wlf -sv_seed 12345

log -r /*; run -all
}
proc run_test {} {
vsim -novopt -64 +acc=npr -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L tblib -L altlib +transport_int_delays +transport_path_delays +notimingchecks -t ps xil_defaultlib.glbl tblib.toplevel_tb +UVM_TESTNAME=base_test +UVM_VERBOSITY=UVM_FULL -l base_test.log -wlf base_test.wlf -sv_seed 12345

log -r /*; run -all
}
